# Uncomment the next line to define a global platform for your project
platform :ios, '10.1'
use_frameworks!

target 'SampleProject' do
    pod 'Alamofire'
    pod 'SwiftyJSON'

end

target 'SampleProjectTests' do

end
